### ISSUE TITLE
Kind request to change the name :trollface: 

### ISSUE THREAD

**Issue by tecM12** [CatCentralGitHub/SimURAI-KitKat#2]
Is it ok if you're able to change the name lol, just because SImURAI isnt actually out & i think its kinda weird to already have a Kitkat version lol.

**Comment by Milanesa1245** [comment]
i dont know, im just here to annoy you, talk to him
yours truly, molana

**Comment by CatCentralGitHub** [comment]
Nah, I mean I *am* on the dev team...

**Comment by tecM12** [comment]
dosent exactly give you rights to leak it according to the agreement (no leaks)
